node {
    
    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ravishsubramanya/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
                    }

        stage('Image') {
            dir ('discovery-service') {
                def app = docker.build "localhost:9010/discovery-service"
                }
        }

        stage ('Run') {
            docker.image("localhost:9010/discovery-service").run('-p 9070:9070 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

}
