node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ravishsubramanya/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
        }

        stage('Image') {
            dir ('gateway-service') {
                def app = docker.build "localhost:9010/gateway-service"
               
            }
        }

        stage ('Run') {
            docker.image("localhost:9010/gateway-service").run('-p 9080:9080 -td -name gateway')
        }
     
    }

}
