node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ravishsubramanya/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('gateway-service') {
                def app = docker.build "localhost:9010/gateway-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:9010/gateway-service:${env.version}").run('-p 9080:9080 -h gateway --name gateway --link discovery --link account --link customer')
        }
     

    }

}
