node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ravishsubramanya/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "localhost:9010/account-service"
               }
        }

        stage ('Run') {
            docker.image("localhost:9010/account-service").run('-p 9050:9050 -td')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}
