node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/ravishsubramanya/sample-spring-microservices.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

        }

        stage('Image') {
            dir ('customer-service') {
                def app = docker.build "localhost:9010/customer-service"
            }
        }

        stage ('Run') {
            docker.image("localhost:9010/customer-service").run('-p 9060:9060 -td --name customerservice')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

}
